name: MLops CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Cambiado de v7 a v5 (versión válida)
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

#      - name: Run tests # (O el siguiente paso que estabas escribiendo)
#        run: |
#          pytest

      - name: Run Data Processing
        run: |
          python src/data/data_processing.py \
            --input_path data/raw/house_data.csv \
            --output_path data/processed/cleaned_house_data.csv
      
      - name: Do Feature Engineering
        run: |
          python src/features/engineering.py \
            --input_path data/processed/cleaned_house_data.csv \
            --output_path data/processed/featured_house_data.csv \
            --preprocessor models/trained/preprocessor.pkl